### ISSUE TITLE
Explorer doesn't prevent user from setting empty or invalid parameters in url

### ISSUE THREAD

**Issue by kenarab** [qbotics/Rpolyhedra-explorer#6]
This is an example [url](https://qbotics.shinyapps.io/rpolyhedra-explorer/?_inputs_&polyhedron_color=""&polyhedron_name=""&polyhedron_source=""&show_axes=false) of this behavior

**Comment by leobelen** [comment]
The issue was created by bogus querystrings. Now it assumes that if the qs is "", then it will act as if it is null.
